### ISSUE TITLE
When restoring, no new revision is created

### ISSUE THREAD

**Issue by SimonSimCity** [nicklozon/meteor-collection-revisions#2]
When I save a document, I have my first version of my document - the initial version. No `revisions`-property has been created on the document so far, right? Now I change something, save it and get my second version. Now the `revisions`-property is set to an array having one document, namely the document in it's first version.

If I now try to revert my document to the first version, my changes, done in my second version, are gone. I would like to have them now stored as a new document in the `revisions` array - that said - now being in the 3rd version ...

**Comment by nicklozon** [comment]
I'm not sure if this is a feature request or a bug, but I'll do some testing to investigate the functionality.

**Comment by nicklozon** [comment]
This commit should have also addressed the else statement  - purging is probably occurring during a restore regardless of whether it is enabled. https://github.com/nicklozon/meteor-collection-revisions/pull/1/commits/da25041f8b64486c61c0cfc097614e46247b3136

Edit: Issue is the aforementioned commit prevents revisions upon restore, which should not happen. Will fix tonight.

**Comment by SimonSimCity** [comment]
I've found a work-around that's quite neat ... just setting all the properties myself will surely set it back to the state it was back then and it will also create a new revision 😉 

So my code went from:
```
CollectionRevisions.restore(Scans._name, scan._id, currentRevision.revisionId);
```
to:
```
delete currentRevision.revisionId;
Scans.update(scan._id, { $set: currentRevision });
```

@nicklozon what do you think? Is it valid to use? Anything I forgot? 😅

**Comment by nicklozon** [comment]
Have you tested that? I don't think a new revision would be created because the lastModifiedField would still exist.

`delete currentRevision.lastModified; // Depends on what you have set for lastModifiedField`

**Comment by nicklozon** [comment]
I've had a chance to test this and I do not see an issue.

I have a document with 1 revision. I restore the only revision and the result is 2 revisions:

```
> Widgets.findOne('5ghf9fLkGBZYhDwx5');
{ _id: '5ghf9fLkGBZYhDwx5',
  name: 'ABC',
  lastModified: Tue May 16 2017 18:02:30 GMT-0400 (EDT),
  revisions: 
   [ { name: 'Widget ABC',
       lastModified: Tue May 16 2017 18:01:50 GMT-0400 (EDT),
       revisionId: 'fLrZX9ZeDBPEM7DWb' } ] }
> CollectionRevisions.restore('Widgets', '5ghf9fLkGBZYhDwx5', 'fLrZX9ZeDBPEM7DWb');
> Widgets.findOne('5ghf9fLkGBZYhDwx5');
{ _id: '5ghf9fLkGBZYhDwx5',
  name: 'Widget ABC',
  lastModified: Tue May 16 2017 18:02:50 GMT-0400 (EDT),
  revisions: 
   [ { name: 'ABC',
       lastModified: Tue May 16 2017 18:02:30 GMT-0400 (EDT),
       revisionId: 'Bbj46GtxkGLJ39doM' },
     { name: 'Widget ABC',
       lastModified: Tue May 16 2017 18:01:50 GMT-0400 (EDT),
       revisionId: 'fLrZX9ZeDBPEM7DWb' } ] }
```

Is this your expectation?

The code is confusing and I thought there was a bug, but the logic makes more sense now.

**Comment by SimonSimCity** [comment]
@nicklozon yes, that's what I expect ... here's a test I wrote, and it fails if I do not wait before calling the restore function:

FYI: Try also removing the line after the `TODO` ... I guess there's another bug I found while writing this test ...

```
/* eslint-disable func-names, prefer-arrow-callback, max-len */
/* eslint-env mocha */

import { Mongo } from 'meteor/mongo';
import { assert } from 'meteor/practicalmeteor:chai';
import { resetDatabase } from 'meteor/xolvio:cleaner';

const Widgets = new Mongo.Collection('widgets');

// TODO: Remove after this bug is fixed: The property callback has no default
CollectionRevisions.defaults.callback = () => {};

Widgets.attachCollectionRevisions();

describe('Revisions', function () {
  beforeEach(function () {
    resetDatabase();
  });

  it('should create a new revision when restoring', function () {
    const widgetId = Widgets.insert({
      name: 'ABC',
    });
    Widgets.update(widgetId, {
      $set: { name: 'ABC' },
    });

    let widget = Widgets.findOne(widgetId);

    CollectionRevisions.restore(Widgets._name, widget._id, widget.revisions[0]);

    widget = Widgets.findOne(widgetId);

    assert.equal(widget.revisions.length, 2);
  });

  it('should create a new revision when waiting before restoring', function (done) {
    this.timeout(10000);

    const widgetId = Widgets.insert({
      name: 'ABC',
    });
    Widgets.update(widgetId, {
      $set: { name: 'ABC' },
    });

    let widget = Widgets.findOne(widgetId);

    Meteor.setTimeout(function () {
      CollectionRevisions.restore(Widgets._name, widget._id, widget.revisions[0]);

      widget = Widgets.findOne(widgetId);

      assert.equal(widget.revisions.length, 2);
      done();
    }, 2000);
  });
});
```

I don't know how much you know about the test-setup I have here, so here's a quick introduction:

To run this code you need to install the packages `practicalmeteor:mocha`, `practicalmeteor:chai` and `xolvio:cleaner`.

Install them, save my code in a file whose name ends by `.test.js` and run `meteor test --driver-package practicalmeteor:mocha --port 3100` on your shell. When it shows `App running at: http://localhost:3100/`, open your browser on http://localhost:3100/ and watch the tests.

**EDIT:** Just found out that my second test (the one with the timeout, that I claimed would succeeded) was wrong... Here's a corrected version - but this also fails however long I take the timeout.

**Comment by nicklozon** [comment]
I'm at work so I can't test this right now, but I think you are performing findOne before the document is actually updated - I don't believe the update is synchronous, so you need to use a callback. The problem is, CollectionRevisions.restore() does not have a callback, but it can be easily added.

Try this:
```
  it('should create a new revision when waiting before restoring', function (done) {
    this.timeout(10000);

    const widgetId = Widgets.insert({
      name: 'ABC',
    });

    Widgets.update(widgetId, {
      $set: { name: 'ABC' },
    }, function(err, docCount) {
      // callback when update is actually complete
      let widget = Widgets.findOne(widgetId);

      CollectionRevisions.restore(Widgets._name, widget._id, widget.revisions[0]);

      // use timeout since restore function does not have a callback
      Meteor.setTimeout(function () {
        widget = Widgets.findOne(widgetId);

        assert.equal(widget.revisions.length, 2);
        done();
      }, 2000);
    });
  });
```

http://docs.meteor.com/api/collections.html#Mongo-Collection-update

I'll add the ability to include a callback in the restore function, so it will look like this:

```
      CollectionRevisions.restore(Widgets._name, widget._id, widget.revisions[0], function(err, recCount) {
        widget = Widgets.findOne(widgetId);

        assert.equal(widget.revisions.length, 2);
        done();
      });
```

**Comment by nicklozon** [comment]
FYI - I fixed the other bug you found with callback not being defined in v0.3.2: https://github.com/nicklozon/meteor-collection-revisions/commit/aa592b96eca0705357954827f2db059eded62913

**Comment by nicklozon** [comment]
So I noticed some things while testing:

1. Don't use resetDatabase() - this is killing server tests because the client test is killing the database when the client goes to do its test. Edit: If you want to have this work, you would need to somehow tell Mocha to run server and client tests synchronously, I'm not sure if that is possible.
2. There was an issue with looking up the Collection object in the code when using Mocha. I'm not sure why, but this issue wasn't happening with meteor shell or the application. The Collection object is expected to be on the global namespace, since it isn't, it fails. I solved this issue by adding a new dependency that provides Collection lookups by name. My tests are working now with v0.3.3 I just published.

I added the callback to the restore function, so this is working for me now:

```
  it('should create a new revision when restoring', function (done) {
    const widgetId = Widgets.insert({
      name: 'Widget ABC',
    });

    Widgets.update(widgetId, {
      $set: { name: 'ABC' },
    }, function(err, docCount) {
      let widget = Widgets.findOne(widgetId);
      CollectionRevisions.restore(Widgets._name, widget._id, widget.revisions[0], function(err, docCount) {
        let widget = Widgets.findOne(widgetId);
        assert.equal(widget.revisions.length, 2);
        done();
      });
    });
  });
```

Let me know if this works for you and I can close this issue.

**Comment by nicklozon** [comment]
Concerning resetDatabase, perhaps this is related: https://github.com/practicalmeteor/meteor-mocha/issues/84

**Comment by SimonSimCity** [comment]
As far as I know, the functions are built in a way that they are synchronous if you don't use the callback.

Actually, if I think about it, you don't need to use the `meteor/xolvio:cleaner` package and can even cover all tests in a `isServer` condition for sequential testing.

But I have to test with the latest version and reduce the dependencies ... this was just a quick shot.

**Comment by SimonSimCity** [comment]
Thanks very much for your time and sorry for bothering ...

I've always run tests against v0.3.1 but now, that I've updated to v0.3.3, it works.
